name: Build, version, and publish container
description: Runs build and publishing of a container image to the container registry, including applying a semantic version.

inputs:
  registryUsername:
    description: The username to use to authenticate with the container registry.
    required: true
  registryPassword:
    description: The token to use to authenticate with the container registry.
    required: true
  imageNames:
    description: The names of the images to tag and publish.
    required: true
  context:
    description: The context to use when building. Defaults to ./
    required: false
    default: ./
  dockerfile:
    description: The dockerfile to build. Defaults to ./Dockerfile
    required: false
    default: ./Dockerfile
  registryHost:
    description: The host of the container registry to push to. Defaults to ghcr.io
    required: false
    default: ghcr.io
  writeSummary:
    description: Whether to write a summary to GitHub. Defaults to true.
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - id: version
      name: Get semantic version
      uses: spritely/actions.semantic-version/get@924ea61c30c155e5cd12ffb1c2505c592926d135 # v0.8.29
      with:
        writeSummary: ${{ inputs.writeSummary }}

    - name: Build and publish container
      uses: spritely/actions.publish-container@73e1c32ce79fa4215a434cbaebb9edb7344d155b # v0.2.97
      with:
        registryUsername: ${{ inputs.registryUsername }}
        registryPassword: ${{ inputs.registryPassword }}
        registryHost: ${{ inputs.registryHost }}
        context: ${{ inputs.context }}
        dockerfile: ${{ inputs.dockerfile }}
        imageNames: ${{ inputs.imageNames }}
        version: ${{ steps.version.outputs.version }}
        writeSummary: ${{ inputs.writeSummary }}

    - name: Apply semantic version
      if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
      uses: spritely/actions.semantic-version/apply@924ea61c30c155e5cd12ffb1c2505c592926d135 # v0.8.29
      with:
        version: ${{ steps.version.outputs.version }}
