version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "**/*"
    schedule:
      interval: daily
    groups:
      all-docker:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directories:
      - "**/*"
    schedule:
      interval: daily
    groups:
      all-docker-compose:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directories:
      - /
      - "**/*"
    schedule:
      interval: daily
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directories:
      - /tests/dotnet-container-test/half-covered/TestProject.UnitTests/
      - /tests/dotnet-package-test/half-covered/TestProject.UnitTests/
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
