name: Build and publish dotnet package
description: Runs build, tests, and publishing of a dotnet package to the package registry, including applying a semantic version.

inputs:
  packageRepository:
    description: The URL of the NuGet package repository to push to.
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  nugetAuthToken:
    description: The NuGet authentication token to use when pushing or pulling packages.
    required: true
  projectFile:
    description: The project file to package such as MyProject.csproj. Do not include the path here.
    required: true
  registryUsername:
    description: The username to use to authenticate with the container registry.
    required: true
  registryPassword:
    description: The token to use to authenticate with the container registry.
    required: true
  projectDirectory:
    description: The directory containing the project to be packaged. Defaults to ./
    required: false
    default: ./
  unitTestProjects:
    # It is important to only pass 'Unit' test projects since the build won't be deployed yet and thus these tests cannot depend on anything in the environment to run
    description: The path to all unit tests projects to run. Defaults to **/*.UnitTests.csproj
    required: false
    default: "**/*.UnitTests.csproj"
  coverageThreshold:
    description: The minimum code coverage percentage required for the build to pass. Defaults to 90
    required: false
    default: "90"
  registryHost:
    description: The host of the container registry to push to. Defaults to ghcr.io
    required: false
    default: ghcr.io
  writeSummary:
    description: Whether to write a summary to GitHub. Defaults to true.
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - id: version
      name: Get semantic version
      uses: spritely/actions.semantic-version/get@v0.5.1
      with:
        writeSummary: ${{ inputs.writeSummary }}

    - name: Unit test with code coverage
      uses: spritely/actions.test-dotnet@v0.3.4
      with:
        nugetAuthToken: ${{ inputs.nugetAuthToken }}
        coverageThreshold: ${{ inputs.coverageThreshold }}
        projectFile: ${{ inputs.projectDirectory }}/${{ inputs.projectFile }}
        unitTestProjects: ${{ inputs.unitTestProjects }}
        # To access private devcontainers
        registryUsername: ${{ inputs.registryUsername }}
        registryPassword: ${{ inputs.registryPassword }}
        registryHost: ${{ inputs.registryHost }}
        writeSummary: ${{ inputs.writeSummary }}

    - name: Build and publish nuget package
      uses: spritely/actions.publish-nuget@v0.2.11
      with:
        packageRepository: ${{ inputs.packageRepository }}
        nugetAuthToken: ${{ inputs.nugetAuthToken }}
        projectFile: ${{ inputs.projectDirectory }}/${{ inputs.projectFile }}
        version: ${{ steps.version.outputs.version }}
        # To access private devcontainers
        registryUsername: ${{ inputs.registryUsername }}
        registryPassword: ${{ inputs.registryPassword }}
        registryHost: ${{ inputs.registryHost }}

    - name: Apply semantic version
      if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
      uses: spritely/actions.semantic-version/apply@v0.5.1
      with:
        version: ${{ steps.version.outputs.version }}
