services:
  build-dev:
    container_name: build-dev
    image: docker.io/spritelydev/dotnet10-devcontainer:0.4.41@sha256:08b56dc20d730e46154897d7798f96be786f2915ae0df5d98e41ee4e7e65a273
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
    # Environment variables have higher precedence than the .env file
    environment:
      - NUGET_TOKEN=${NUGET_TOKEN}
    network_mode: "host"
