services:
  build-dev:
    container_name: build-dev
    image: docker.io/spritelydev/dotnet8-devcontainer:0.3.4
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
    # Environment variables have higher precedence than the .env file
    environment:
      - NUGET_TOKEN=${NUGET_TOKEN}
    network_mode: "host"
