services:
  build-dev:
    container_name: build-dev
    build:
      dockerfile: Dockerfile
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
  build-package-registry:
    container_name: build-package-registry
    image: loicsharma/baget:0.4.0-preview2
    ports:
      - "5001:80"
    environment:
      - ApiKey=fake-token
