name: Build, version, and publish container
description: Runs build and publishing of a container image to the container registry, including applying a semantic version.

inputs:
  registryUsername:
    description: The username to use to authenticate with the container registry.
    required: true
  registryPassword:
    description: The token to use to authenticate with the container registry.
    required: true
  imageNames:
    description: The names of the images to tag and publish.
    required: true
  context:
    description: The context to use when building. Defaults to ./src/
    required: false
    default: ./src/
  dockerfile:
    description: The dockerfile to build. Defaults to ./src/Dockerfile
    required: false
    default: ./src/Dockerfile
  registryHost:
    description: The host of the container registry to push to. Defaults to ghcr.io
    required: false
    default: ghcr.io
  workingDirectory:
    description: The directory to run the git commands in. Defaults to ./src/
    required: false
    default: ./src/
  buildVersion:
    description: The version reference to use when calling nested actions. Defaults to master
    required: false
    default: master

runs:
  using: composite
  steps:
    - id: version
      name: Get semantic version
      uses: spritely/build/steps/get-semantic-version@improve-reuse
      with:
        workingDirectory: ${{ inputs.workingDirectory }}

    - name: Build and publish container
      uses: spritely/build/steps/container-build@improve-reuse
      with:
        registryUsername: ${{ inputs.registryUsername }}
        registryPassword: ${{ inputs.registryPassword }}
        registryHost: ${{ inputs.registryHost }}
        context: ${{ inputs.context }}
        dockerfile: ${{ inputs.dockerfile }}
        imageNames: ${{ inputs.imageNames }}
        version: ${{ steps.version.outputs.version }}

    - name: Apply semantic version
      if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
      uses: spritely/build/steps/apply-semantic-version@improve-reuse
      with:
        version: ${{ steps.version.outputs.version }}
        workingDirectory: ${{ inputs.workingDirectory }}
