name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write # To be able to apply semantic version tags to the repository

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@v0.3.0

      - name: Create .env for build
        shell: bash
        run: |
          cat > ./.devcontainer/.env <<EOF
          EOF

      - id: setup-tests
        name: Setup test container registry
        run: |
          mkdir -p test-results

          docker run -d -p 5000:5000 \
              -v ${{ github.workspace }}/tests/auth:/auth \
              -e REGISTRY_AUTH=htpasswd \
              -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
              -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
              --name registry registry:2

      - name: Run test - container-test
        uses: ./tests/container-test

      - name: Run test - dotnet-container-test
        uses: ./tests/dotnet-container-test

      - name: Add test report title
        if: always()
        shell: bash
        run: echo "# Test Results" >> $GITHUB_STEP_SUMMARY

      - name: Generate test report
        uses: dorny/test-reporter@v2.0.0
        if: always()
        with:
          name: Test Results
          path: test-results/*.xml
          reporter: java-junit

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@v0.3.0
        with:
          version: ${{ steps.version.outputs.version }}
